### ISSUE TITLE
Identifo Admin: Update application: Can't set the authorization way to "internal"

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#213]
Can't set the authorization way to "internal" when updating the application:
https://www.loom.com/share/b42583fbc6ae4a779c854657123b97d6

**Comment by kazemisoroush** [comment]
![image](https://user-images.githubusercontent.com/8931595/133377982-99ef1930-7e77-4590-bea2-5159beba613f.png)
```
vendors~bundle.923966284db456e2060d.bundle.js:36 Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at a (https://identifo.dev.evergen.technology/adminpanel/vendors~bundle.923966284db456e2060d.bundle.js:36:260)
    at s (https://identifo.dev.evergen.technology/adminpanel/vendors~bundle.923966284db456e2060d.bundle.js:36:530)
    at Ka (https://identifo.dev.evergen.technology/adminpanel/vendors~bundle.923966284db456e2060d.bundle.js:36:95127)
    at eo (https://identifo.dev.evergen.technology/adminpanel/vendors~bundle.923966284db456e2060d.bundle.js:36:55996)
    at Object.onBeforeChange (https://identifo.dev.evergen.technology/adminpanel/bundle.923966284db456e2060d.bundle.js:1:173086)
    at https://identifo.dev.evergen.technology/adminpanel/vendors~bundle.923966284db456e2060d.bundle.js:13:112960
    at pt (https://identifo.dev.evergen.technology/adminpanel/vendors~bundle.923966284db456e2060d.bundle.js:13:129425)
    at uo (https://identifo.dev.evergen.technology/adminpanel/vendors~bundle.923966284db456e2060d.bundle.js:13:205328)
    at Ca.lo (https://identifo.dev.evergen.technology/adminpanel/vendors~bundle.923966284db456e2060d.bundle.js:13:205626)
    at https://identifo.dev.evergen.technology/adminpanel/vendors~bundle.923966284db456e2060d.bundle.js:13:184835
```

**Comment by kazemisoroush** [comment]
```
Uncaught (in promise) Error: Error: Error: Request failed with status code 500
    at bundle.923966284db456e2060d.bundle.js:1
    at f (vendors~polyfill.923966284db456e2060d.bundle.js:1)
    at Generator._invoke (vendors~polyfill.923966284db456e2060d.bundle.js:1)
    at Generator.forEach.t.<computed> [as next] (vendors~polyfill.923966284db456e2060d.bundle.js:1)
    at cn (bundle.923966284db456e2060d.bundle.js:1)
    at i (bundle.923966284db456e2060d.bundle.js:1)
```
